[project]
name = "pytest-fahhh"
version = "1.0.0"
description = "A pytest plugin that plays FAHHH meme sound when a test session fails."
readme = "README.md"
authors = [
    { name = "deepaerial", email = "devaeial@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "playsound3>=3.3.1",
]

[project.entry-points."pytest11"]
pytest-fahhh = "pytest_fahhh.plugin"

[project.scripts]
pytest-fahhh = "pytest_fahhh:main"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "tox>=4.20",
    "tox-uv>=1.20",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
